/**
 * Chart data for the Constellations view (WI-032, REQ-015): one small file
 * per constellation under public/charts/, generated by scripts/build-charts.py
 * from d3-celestial (BSD-3-Clause; see public/charts/ATTRIBUTION.md).
 *
 * Loaded when a constellation is chosen, never before, and kept once loaded.
 * This module is content, not astronomy: it knows nothing of time or place.
 * A file that is missing or malformed yields null and the view says so; it
 * never throws.
 */

export interface ChartStar {
  readonly raDeg: number;
  readonly decDeg: number;
  readonly mag: number;
  /** The star's name when it is one of the chart's named stars; else "". */
  readonly name: string;
}

export interface Chart {
  readonly abbr: string;
  readonly name: string;
  readonly genitive: string;
  /** Brightest first. */
  readonly stars: readonly ChartStar[];
  /** The figure: polylines of [RA°, Dec°]. */
  readonly lines: readonly (readonly (readonly [number, number])[])[];
}

const isNum = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);
const isPair = (v: unknown): v is readonly [number, number] =>
  Array.isArray(v) && v.length === 2 && isNum(v[0]) && isNum(v[1]) &&
  v[0] >= 0 && v[0] < 360 && Math.abs(v[1]) <= 90;

/** A chart from its JSON, or null when the shape is not what the painter expects. */
export function parseChart(raw: unknown): Chart | null {
  if (typeof raw !== "object" || raw === null) return null;
  const o = raw as Record<string, unknown>;
  if (typeof o["abbr"] !== "string" || typeof o["name"] !== "string") return null;
  if (!Array.isArray(o["stars"]) || !Array.isArray(o["lines"])) return null;
  const stars: ChartStar[] = [];
  for (const s of o["stars"]) {
    if (!Array.isArray(s) || s.length !== 4 || !isPair([s[0], s[1]]) || !isNum(s[2]) || typeof s[3] !== "string") return null;
    stars.push({ raDeg: s[0] as number, decDeg: s[1] as number, mag: s[2] as number, name: s[3] as string });
  }
  const lines: (readonly [number, number])[][] = [];
  for (const poly of o["lines"]) {
    if (!Array.isArray(poly) || poly.length < 2 || !poly.every(isPair)) return null;
    lines.push(poly.map((p) => [p[0], p[1]] as const));
  }
  if (stars.length === 0) return null;
  return {
    abbr: o["abbr"],
    name: o["name"],
    genitive: typeof o["genitive"] === "string" ? o["genitive"] : "",
    stars,
    lines,
  };
}

export interface ChartLoader {
  /** The chart for a constellation by its catalog name; null when there is none. */
  load(name: string): Promise<Chart | null>;
}

/** Fetch JSON relative to the page; null on any failure. */
async function getJson(url: string): Promise<unknown> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return (await res.json()) as unknown;
  } catch {
    return null;
  }
}

/**
 * A loader over `base` (the charts directory, relative to the page). The
 * index (name → file) is fetched once; each chart once; both are kept.
 */
export function chartLoader(base = "charts/"): ChartLoader {
  let index: Promise<Readonly<Record<string, string>> | null> | null = null;
  const charts = new Map<string, Promise<Chart | null>>();
  const indexOnce = (): Promise<Readonly<Record<string, string>> | null> => {
    if (index === null) {
      index = getJson(`${base}index.json`).then((raw) => {
        if (typeof raw !== "object" || raw === null) return null;
        const out: Record<string, string> = {};
        for (const [k, v] of Object.entries(raw as Record<string, unknown>)) {
          if (typeof v === "string" && /^[A-Za-z0-9]+$/.test(v)) out[k] = v;
        }
        return out;
      });
    }
    return index;
  };
  return {
    load: async (name: string): Promise<Chart | null> => {
      const idx = await indexOnce();
      const abbr = idx?.[name];
      if (abbr === undefined) return null;
      let hit = charts.get(abbr);
      if (hit === undefined) {
        hit = getJson(`${base}${abbr}.json`).then(parseChart);
        charts.set(abbr, hit);
      }
      return hit;
    },
  };
}
